name: High vulns Snyk PR scan

on: pull_request

jobs:
  docker-build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: [prom-pushgateway, guacd]
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t dwpdigital/${{ matrix.image }}:latest ./${{ matrix.image }}/
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: dwpdigital/${{ matrix.image }}
          args: --file=${{ matrix.image }}/Dockerfile --severity-threshold=high --exclude-base-image-vulns --org=dwp-dataworks
